export const GET_TEAM_MEMBERS = 'GET_TEAM_MEMBERS';
export const GET_SURVEY_MEMBERS = 'GET_SURVEY_MEMBERS';
export const SET_MEMBER = 'SET_MEMBER';
export const ADD_MEMBER = 'ADD_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const EDIT_MEMBER = 'EDIT_MEMBER';
